all: D1 D2 D3 D4 D5 D6 D8 D9

D1: D1.s D1-main.c
	gcc -O1 -m32 D1.s D1-main.c -o D1

D2: D2.s D2-main.c
	gcc -O1 -m32 D2.s D2-main.c -o D2

D3: D3.s D3-main.c
	gcc -O1 -m32 D3.s D3-main.c -o D3

D4: D4.s D4-main.c
	gcc -O1 -m32 D4.s D4-main.c -o D4

D5: D5.s D5-main.c
	gcc -O1 -m32 D5.s D5-main.c -o D5

D6: D6.s D6-main.c
	gcc -O1 -m32 D6.s D6-main.c -o D6

D8: D8.s D8-main.c
	gcc -O1 -m32 D8.s D8-main.c -o D8

D9: D9.s D9-main.c
	gcc -O1 -m32 D9.s D9-main.c -o D9

