all: B1 B2 B3 B4 B5 B6 B7 B8 B9

B1: B1.s B1-main.c
	gcc -O1 -m32 B1.s B1-main.c -o B1

B2: B2.s B2-main.c
	gcc -O1 -m32 B2.s B2-main.c -o B2

B3: B3.s B3-main.c
	gcc -O1 -m32 B3.s B3-main.c -o B3

B4: B4.s B4-main.c
	gcc -O1 -m32 B4.s B4-main.c -o B4

B5: B5.s B5-main.c
	gcc -O1 -m32 B5.s B5-main.c -o B5

B6: B6.s B6-main.c
	gcc -O1 -m32 B6.s B6-main.c -o B6

B7: B7.s B7-main.c
	gcc -O1 -m32 B7.s B7-main.c -o B7

B8: B8.s B8-main.c
	gcc -O1 -m32 B8.s B8-main.c -o B8

B9: B9.s B9-main.c
	gcc -O1 -m32 B9.s B9-main.c -o B9
